export D1="/mnt/d1"
export EDITOR="nvim"
export HOST="8700k"
export MOUNT="/mnt/media"
export AUR="$D1/aur"
export CACHE="$HOME/.cache"
export CODE="$D1/code"
export DOWNLOADS="$D1/files/downloads"
export FILES="$D1/files"
export TRASH="$D1/trash"
export WORK="$D1/work"

export ASDF_DATA_DIR="$CACHE/asdf"
export GOBIN="$HOME/.local/bin/go"
export GOCACHE="$CACHE/go/build"
export GOMODCACHE="$CACHE/go/lib/pkg/mod"
export GOPATH="$CACHE/go/lib"
export GOROOT="$CACHE/go/bin"
export LF_BOOKMARKS_PATH="$XDG_CONFIG_HOME/lf/bookmarks"
export NOTES="$FILES/notes"
export NPM_CONFIG_CACHE="$CACHE/npm"
export RECORDINGS="$FILES/recordings"
export SCREENSHOTS="$FILES/screenshots"
export WALLPAPERS="$FILES/wallpapers"
export YARN_CACHE_FOLDER="$CACHE/yarn"

[[ ! "$PATH" =~ "$HOME/.local/bin" ]] && export PATH="$PATH:$HOME/.local/bin"
[[ ! "$PATH" =~ "$GOPATH/bin" ]] && export PATH="$PATH:$GOPATH/bin"
[[ ! "$PATH" =~ "$JAI_DIR" ]] && export PATH="$PATH:${JAI_DIR}/bin"
