set --export D1 "/mnt/d1"
set --export EDITOR "nvim"
set --export HOST "8700k"
set --export MOUNT "/mnt/media"
set --export AUR "$D1/aur"
set --export CACHE "$HOME/.cache"
set --export CODE "$D1/code"
set --export FILES "$D1/files"
set --export TRASH "$D1/trash"
set --export WORK "$D1/work"

set --export DOWNLOADS "$FILES/downloads"
set --export FVM_HOME "$CACHE/fvm"
set --export GOBIN "$HOME/.local/bin/go"
set --export GOCACHE "$CACHE/go/build"
set --export GOMODCACHE "$CACHE/go/lib/pkg/mod"
set --export GOPATH "$CACHE/go/lib"
set --export GOROOT "$CACHE/go/bin"
set --export NOTES "$FILES/notes"
set --export NPM_CONFIG_CACHE "$CACHE/npm"
set --export NVM_DIR "$CACHE/nvm"
set --export RECORDINGS "$FILES/recordings"
set --export SCREENSHOTS "$FILES/screenshots"
set --export WALLPAPERS "$FILES/wallpapers"
set --export YARN_CACHE_FOLDER "$CACHE/yarn"

set --export NNN_BMS "0://;1:$D1;a:$AUR;c:$CODE;d:$DOWNLOADS;f:$FILES;m:$MOUNT;n:$NOTES;r:$RECORDINGS;s:$SCREENSHOTS;t:$TRASH;w:$WORK"

function display_layout --description "Set display's layout"
	bash -i -c "display_layout $argv"
end
