export D1="/mnt/d1"
export EDITOR="nvim"
export HOST="nuc8i3"
export MOUNT="/mnt/media"
export AUR="$HOME/aur"
export CACHE="$HOME/.cache"
export DOWNLOADS="$HOME/files/downloads"
export FILES="$HOME/files"
export NOTES="$FILES/notes"
export TRASH="$HOME/trash"
export LF_BOOKMARKS_PATH="$XDG_CONFIG_HOME/lf/bookmarks"

[[ ! "$PATH" =~ $HOME/.local/bin ]] && export PATH="$PATH:$HOME/.local/bin"
