set --export EDITOR "nvim"
set --export HOST "nuc8i3"
set --export MOUNT "/mnt/media"
set --export AUR "$HOME/aur"
set --export CACHE "$HOME/.cache"
set --export CODE "$HOME/code"
set --export DOWNLOADS "$HOME/files/downloads"
set --export FILES "$HOME/files"
set --export TRASH "$HOME/trash"
set --export WORK "$HOME/work"

set --export NNN_BMS "0://;a:$AUR;c:$CODE;d:$DOWNLOADS;f:$FILES;m:$MOUNT;n:$NOTES;r:$RECORDINGS;s:$SCREENSHOTS;t:$TRASH;w:$WORK"
