set --export EDITOR "nvim"
set --export HOST "nuc8hvk"
set --export MOUNT "/mnt/media"
set --export AUR "$HOME/aur"
set --export CACHE "$HOME/.cache"
set --export CODE "$HOME/code"
set --export DOWNLOADS "$HOME/files/downloads"
set --export FILES "$HOME/files"
set --export TRASH "$HOME/trash"
set --export WORK "$HOME/work"

set --export ASDF_DATA_DIR "$CACHE/asdf"
set --export GOBIN "$HOME/.local/bin/go"
set --export GOCACHE "$CACHE/go/build"
set --export GOMODCACHE "$CACHE/go/lib/pkg/mod"
set --export GOPATH "$CACHE/go/lib"
set --export GOROOT "$CACHE/go/bin"
set --export NOTES "$FILES/notes"
set --export NPM_CONFIG_CACHE "$CACHE/npm"
set --export RECORDINGS "$FILES/recordings"
set --export SCREENSHOTS "$FILES/screenshots"
set --export WALLPAPERS "$FILES/wallpapers"
set --export YARN_CACHE_FOLDER "$CACHE/yarn"

set --export NNN_BMS "0://;a:$AUR;c:$CODE;d:$DOWNLOADS;f:$FILES;m:$MOUNT;n:$NOTES;r:$RECORDINGS;s:$SCREENSHOTS;t:$TRASH;w:$WORK"
